---
Name: mysiteconfig
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SiteTree:
  extensions:
    - WorkflowEmbargoExpiryExtension
SSViewer:
  theme: 'starter'
MySQLDatabase:
  connection_charset: 'utf8'
LeftAndMain:
  help_link: "https://www.cwp.govt.nz/user-help/"
VersionFeed:
  allchanges_enabled: false
  changes_enabled: false
MultiValueField:
  disable_unserialize: true
