---
Name: cwpcoreenvironmentchecks
---
SilverStripe\EnvironmentCheck\EnvironmentCheckSuite:
  registered_checks:
    db:
      definition: 'SilverStripe\EnvironmentCheck\Checks\DatabaseCheck()'
      title: 'Is the database accessible?'
  registered_suites:
    health:
      - db

---
Name: cwpcoresolrenvironmentcheck
Only:
  moduleexists: 'cwp/cwp-search'
---
SilverStripe\EnvironmentCheck\EnvironmentCheckSuite:
  registered_checks:
    solr:
      definition: 'SilverStripe\EnvironmentCheck\Checks\SolrIndexCheck()'
      title: 'Are all Solr indexes available?'
  registered_suites:
    health:
      - solr
